from abc import ABC,abstractmethod
class PlatformAdapter(ABC):
 @abstractmethod
 def discover_competitors(self,business): ...
 @abstractmethod
 def get_products(self,competitor): ...
 @abstractmethod
 def get_prices(self,competitor): ...
 @abstractmethod
 def get_reviews(self,competitor): ...
 @abstractmethod
 def get_promotions(self,competitor): ...
