-- Global, platform-agnostic logical schema.
CREATE TABLE IF NOT EXISTS businesses (id TEXT PRIMARY KEY, name TEXT NOT NULL, country_code CHAR(2) NOT NULL, business_type TEXT NOT NULL, channel TEXT NOT NULL, location TEXT, website_url TEXT, goal TEXT);
CREATE TABLE IF NOT EXISTS platform_connections (id TEXT PRIMARY KEY, business_id TEXT NOT NULL, country_code CHAR(2) NOT NULL, platform TEXT NOT NULL, category TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', capabilities_json TEXT NOT NULL DEFAULT '[]');
CREATE TABLE IF NOT EXISTS competitors (id TEXT PRIMARY KEY, business_id TEXT NOT NULL, name TEXT NOT NULL, platform TEXT NOT NULL, strategic BOOLEAN NOT NULL DEFAULT FALSE, similarity_score REAL NOT NULL DEFAULT 0, market_relevance REAL NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, competitor_id TEXT NOT NULL, name TEXT NOT NULL, category TEXT, current_price REAL, currency TEXT);
CREATE TABLE IF NOT EXISTS snapshots (id TEXT PRIMARY KEY, competitor_id TEXT NOT NULL, captured_at TEXT NOT NULL, payload_json TEXT NOT NULL, source TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS changes (id TEXT PRIMARY KEY, competitor_id TEXT NOT NULL, type TEXT NOT NULL, before_json TEXT, after_json TEXT, detected_at TEXT NOT NULL, magnitude REAL NOT NULL DEFAULT 0, severity TEXT NOT NULL DEFAULT 'info', impact_score REAL NOT NULL DEFAULT 0, confidence REAL NOT NULL DEFAULT 0, evidence_json TEXT NOT NULL DEFAULT '[]', source TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS reviews (id TEXT PRIMARY KEY, competitor_id TEXT NOT NULL, rating REAL, text TEXT NOT NULL, created_at TEXT NOT NULL, sentiment TEXT, topics_json TEXT NOT NULL DEFAULT '[]', source TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS cost_signals (id TEXT PRIMARY KEY, product_id TEXT, type TEXT NOT NULL, name TEXT NOT NULL, before_value REAL, after_value REAL, unit TEXT, observed_at TEXT NOT NULL, source TEXT NOT NULL, confidence REAL NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS predictions (id TEXT PRIMARY KEY, competitor_id TEXT NOT NULL, prediction_type TEXT NOT NULL, predicted_at TEXT NOT NULL, expected_window_days INTEGER NOT NULL, probability REAL NOT NULL, evidence_json TEXT NOT NULL DEFAULT '[]', outcome TEXT, outcome_at TEXT);
